# Generated by Django 6.1.1 on 2026-09-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_checkout_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provisioning_checked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='provisioning_error',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='provisioning_lease',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='provisioning_payload',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='provisioning_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='provisioning_status',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='provisioning_vmid',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='provisioning_vps_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
