# Generated by Django 6.1.1 on 2026-09-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_order_provisioning_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='XenditCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='XENDIT', editable=False, max_length=20)),
                ('reference_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('payment_session_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_link_url', models.URLField(blank=True, max_length=2048)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CREATING', 'Creating checkout'), ('ACTIVE', 'Awaiting payment'), ('UNKNOWN', 'Needs reconciliation'), ('VERIFYING', 'Verifying payment'), ('COMPLETED', 'Payment confirmed'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='CREATING', max_length=20)),
                ('verified_payment_id', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='billing.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['CREATING', 'ACTIVE', 'UNKNOWN', 'VERIFYING'])), fields=('order',), name='one_open_xendit_checkout_per_order')],
            },
        ),
    ]
